name: Build and Analyze with SonarCloud

on:
  workflow_dispatch:  # Allows manual triggering of the workflow
  push:
    branches:
      - main  # Runs on push to the main branch
  pull_request:
    types: [opened, synchronize, reopened]  # Runs on pull request events (opened, synchronized, reopened)

jobs:
  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch full history to ensure SonarCloud can analyze branches correctly

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'  # Specify the Node.js version (adjust as necessary) 

      # Run SonarCloud analysis
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          organization: ${{ secrets.SONAR_ORG }}  
          projectKey: ${{ secrets.SONAR_PROJECT_KEY }}  
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  
