name: Node.js CI with SonarCloud

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'  # Cache npm dependencies

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run tests and collect coverage
      - name: Run tests
        run: npm test -- --coverage  # Modify this if you have a different test command

      # Run SonarCloud scan
      - name: Run SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}

      # Optional: Upload coverage to SonarCloud (if coverage report is required)
      - name: Upload coverage report
        run: |
          npx sonar-scanner \
          -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
          -Dsonar.organization=${{ secrets.SONAR_ORG }} \
          -Dsonar.sources=. \
          -Dsonar.tests=. \
          -Dsonar.test.inclusions=**/*.test.js \
          -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
