name: Node.js CI with SonarCloud

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'  # Cache npm dependencies

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Install Java 17
      - name: Install Java 17
        run: |
          sudo apt-get update
          sudo apt-get install openjdk-17-jdk -y   

      # Run SonarCloud scan
      - name: Run SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
